name: Waka Readme

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"


jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: MistyyBoi/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_TIME }}
          SHOW_TITLE: true
          